id: P2472344E
initial_creation_type: input
source_metadata:
  title: Averting Obstacles
  language: fr
  description: 'A series of apotropaic practices and rites for averting obstacles
    and dispelling negativity:'
  volume:
    ec991c968d1f42ea8ee1ecb620b22f9c:
      title: The Ultimate, Natural Dispeller of Obstacles
      parent: General
    d39390bad4c94ec1b2194c31ab713716:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    a7253594548e4a6397331bace9ca22cf:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Other
    69494babf74445ff9086384895082dae:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Other
    e137e1931bcc4c22b7b466736f1b30dc:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Repelling Invasion
    d77615adfa224970aba0d6dfcc452fb5:
      title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
      parent: Repelling Invasion
    b4aea0db075641ba9f5160233603ddcc:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    76706e55f09d425ba5a869ca97a5a968:
      title: Averting Obstacles through Sitātapatrā
      parent: Sitātapatrā
    396c8968ac8f4936988733314b144fcd:
      title: A Short Practice for Averting Obstacles through Vajrakīla
      parent: Vajrakīla
created_at: '2022-03-01T02:55:09.614018'
last_modified_at: '2022-03-01T02:55:09.614020'
